add_item:
  name: Add Item
  description: Add a new pantry item
  fields:
    name:
      description: Name of the item
      example: Canned Beans
      required: true
      selector:
        text:
    quantity:
      description: Current quantity in stock
      example: 5
      required: true
      selector:
        number:
          min: 0
          step: 1
    min_quantity:
      description: Minimum required quantity
      example: 3
      required: true
      selector:
        number:
          min: 0
          step: 1
    expiration_dates:
      description: List of expiration dates (YYYY-MM-DD)
      required: false
      default: []
      selector:
        date:
          multiple: true

update_item:
  name: Update Item
  description: Update an existing pantry item
  fields:
    item_id:
      description: Index of the item to update
      required: true
      selector:
        number:
          min: 0
          step: 1
    item:
      description: New item data
      required: true
      selector:
        object:
          fields:
            name: 
              selector: { text: {} }
            quantity: 
              selector: { number: { min: 0, step: 1 } }
            min_quantity: 
              selector: { number: { min: 0, step: 1 } }
            expiration_dates:
              selector: { date: { multiple: true } }

delete_item:
  name: Delete Item
  description: Delete an item from the pantry
  fields:
    item_id:
      description: Index of the item to delete
      required: true
      selector:
        number:
          min: 0
          step: 1