add_item:
  name: Add Item
  description: Add a new food item or additional quantities/expirations of an existing item
  fields:
    item_name:
      description: "Name of the item (e.g. Canned soup)."
      example: "Canned soup"
    quantity:
      description: "Quantity to add."
      example: 2
    expiration_dates:
      description: "List of expiration dates (YYYY-MM-DD)."
      example: ["2025-12-31"]

edit_item:
  name: Edit Item
  description: Edit the existing item’s minimum quantity
  fields:
    item_name:
      description: "Name of the item to edit."
      example: "Canned soup"
    min_quantity:
      description: "New minimum quantity"
      example: 5

remove_item:
  name: Remove Item
  description: Remove certain quantity of an item or specific expiration dates
  fields:
    item_name:
      description: "Name of the item to remove from."
      example: "Canned soup"
    quantity:
      description: "Quantity to remove."
      example: 1
    expiration_dates:
      description: "Specific expiration dates to remove if needed (YYYY-MM-DD). Leave empty to remove from earliest first."
      example: ["2025-12-31"]
